import { BRAND } from "./config";

export function createStyles(isMobile, isTablet) {
  const compact = isMobile || isTablet;
  return {
    page: {
      minHeight: "100vh",
      background: BRAND.cream,
      padding: compact ? "12px" : "28px",
      fontFamily: "Inter, Arial, sans-serif",
      overflowX: "hidden",
      boxSizing: "border-box",
    },
    container: { width: "100%", maxWidth: "1120px", margin: "0 auto", boxSizing: "border-box" },
    header: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: isMobile ? "8px" : "16px",
      background: BRAND.white,
      border: `1px solid ${BRAND.sky}`,
      borderRadius: isMobile ? "18px" : "24px",
      padding: isMobile ? "10px 12px" : "14px 18px",
      marginBottom: isMobile ? "14px" : "24px",
      boxShadow: "0 12px 30px rgba(26,35,50,0.10)",
      boxSizing: "border-box",
    },
    brandWrap: { display: "flex", alignItems: "center", gap: isMobile ? "10px" : "18px", cursor: "pointer", minWidth: 0 },
    logoImage: { width: isMobile ? "58px" : "88px", height: isMobile ? "44px" : "58px", objectFit: "contain", flexShrink: 0 },
    brandTitle: { color: BRAND.navy, fontSize: isMobile ? "22px" : "30px", fontWeight: 1000, lineHeight: 1.05, whiteSpace: isMobile ? "normal" : "nowrap" },
    subtitle: { color: BRAND.taupe, fontSize: isMobile ? "13px" : "14px", fontWeight: 700, letterSpacing: "0.6px" },
    logoBoxSmall: { width: isMobile ? "42px" : "52px", height: isMobile ? "42px" : "52px", borderRadius: isMobile ? "14px" : "18px", background: BRAND.gold, display: "grid", placeItems: "center", flexShrink: 0 },
    nameCard: {
      background: BRAND.cream,
      border: `1px solid ${BRAND.sky}`,
      borderRadius: isMobile ? "26px" : "34px",
      boxShadow: "0 22px 55px rgba(26,35,50,0.14)",
      padding: isMobile ? "34px 20px" : "54px",
      textAlign: "center",
      display: "grid",
      gap: "18px",
      justifyItems: "center",
    },
    nameInput: {
      width: "100%",
      maxWidth: "420px",
      border: `2px solid ${BRAND.sky}`,
      borderRadius: "20px",
      padding: "16px 18px",
      fontSize: "18px",
      color: BRAND.navy,
      background: BRAND.white,
      outline: "none",
      boxSizing: "border-box",
      textAlign: "center",
      fontWeight: 800,
    },
    infoGrid: {
      display: "grid",
      gridTemplateColumns: compact ? "1fr" : "repeat(3, 1fr)",
      gap: compact ? "10px" : "14px",
      margin: compact ? "28px 0" : "36px 0",
    },
    infoCard: {
      border: `2px solid ${BRAND.sky}`,
      borderRadius: "22px",
      padding: isMobile ? "14px" : "18px 12px",
      color: BRAND.navy,
      background: BRAND.white,
      boxShadow: "0 10px 24px rgba(46,78,123,0.08)",
      textAlign: "center",
      display: "flex",
      flexDirection: isMobile ? "row" : "column",
      justifyContent: "center",
      alignItems: "center",
      gap: isMobile ? "8px" : "4px",
    },
    mainButton: {
      width: compact ? "100%" : "auto",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "10px",
      border: "none",
      borderRadius: "22px",
      padding: isMobile ? "16px 20px" : "17px 30px",
      background: BRAND.gold,
      color: BRAND.navy,
      fontWeight: 1000,
      fontSize: isMobile ? "16px" : "17px",
      cursor: "pointer",
      boxShadow: "0 16px 34px rgba(243,164,11,0.28)",
    },
    microText: { marginTop: "18px", color: BRAND.taupe, fontWeight: 800, fontSize: isMobile ? "14px" : "15px" },
    quizCard: {
      background: BRAND.cream,
      border: `1px solid ${BRAND.sky}`,
      borderRadius: isMobile ? "26px" : "34px",
      boxShadow: "0 22px 55px rgba(26,35,50,0.14)",
      overflow: "hidden",
    },
    quizTop: { display: "flex", flexDirection: isMobile ? "column" : "row", justifyContent: "space-between", gap: "14px", padding: isMobile ? "24px 20px 0" : "36px 42px 0" },
    meta: { color: BRAND.taupe, marginTop: "6px", textTransform: "capitalize", fontWeight: 800 },
    topBadges: { display: "flex", gap: "10px", flexWrap: "wrap" },
    timerBadge: {
      display: "flex",
      alignItems: "center",
      gap: "6px",
      background: BRAND.gold,
      color: BRAND.navy,
      borderRadius: "999px",
      padding: "10px 15px",
      fontWeight: 1000,
      height: "fit-content",
    },
    scoreBadge: {
      background: BRAND.sky,
      color: BRAND.navy,
      borderRadius: "999px",
      padding: "10px 15px",
      fontWeight: 1000,
      height: "fit-content",
    },
    progressOuter: { height: "12px", background: "rgba(156,202,238,0.35)", borderRadius: "999px", overflow: "hidden", margin: isMobile ? "22px 20px" : "28px 42px" },
    progressOuterBig: { height: "16px", background: "rgba(156,202,238,0.35)", borderRadius: "999px", overflow: "hidden", margin: "26px 0" },
    progressInner: { height: "100%", background: BRAND.gold, borderRadius: "999px", transition: "width 300ms ease" },
    questionBox: { margin: isMobile ? "0 20px 22px" : "0 42px 34px", padding: isMobile ? "26px 18px" : "42px", borderRadius: isMobile ? "24px" : "30px", background: `linear-gradient(135deg, ${BRAND.navy}, ${BRAND.deep})`, textAlign: "center" },
    questionText: { color: BRAND.cream, fontSize: isMobile ? "25px" : isTablet ? "34px" : "42px", lineHeight: 1.18, margin: 0 },
    optionsGrid: { display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(2, minmax(0, 1fr))", gap: isMobile ? "12px" : "16px", padding: isMobile ? "0 20px 28px" : "0 42px 38px" },
    answerButton: {
      minHeight: isMobile ? "64px" : "82px",
      border: "2px solid",
      borderRadius: isMobile ? "18px" : "26px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      padding: isMobile ? "12px" : "16px",
      fontSize: isMobile ? "17px" : "21px",
      fontWeight: 1000,
      cursor: "pointer",
      textAlign: "center",
      lineHeight: 1.2,
    },
    answerLetter: { opacity: 0.9, flexShrink: 0 },
    feedbackBox: { margin: isMobile ? "0 20px 28px" : "0 42px 42px", padding: isMobile ? "18px" : "22px", borderRadius: "24px", background: BRAND.white, border: `1px solid ${BRAND.sky}`, textAlign: isMobile ? "center" : "left" },
    feedbackText: { color: BRAND.taupe, fontSize: "15px", lineHeight: 1.45, margin: "8px 0 0" },
    mainButtonSmall: {
      width: compact ? "100%" : "auto",
      border: "none",
      borderRadius: "18px",
      padding: "13px 22px",
      background: BRAND.gold,
      color: BRAND.navy,
      fontWeight: 1000,
      cursor: "pointer",
      marginTop: "14px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
    },
    finishCard: { background: BRAND.cream, border: `1px solid ${BRAND.sky}`, borderRadius: isMobile ? "26px" : "34px", boxShadow: "0 22px 55px rgba(26,35,50,0.14)", overflow: "hidden" },
    finishCenter: { maxWidth: "720px", margin: "0 auto", textAlign: "center", padding: isMobile ? "34px 20px 20px" : "48px 32px 24px" },
    trophyBox: { width: isMobile ? "74px" : "90px", height: isMobile ? "74px" : "90px", borderRadius: "28px", background: BRAND.gold, display: "grid", placeItems: "center", margin: "0 auto 18px" },
    finalScore: { color: BRAND.navy, fontSize: isMobile ? "48px" : "64px", margin: "10px 0", lineHeight: 1 },
    answerList: { padding: isMobile ? "8px 20px 28px" : "10px 42px 42px", display: "grid", gap: "12px" },
    scoreRow: {
      display: "flex",
      justifyContent: "space-between",
      gap: "12px",
      padding: isMobile ? "14px" : "18px",
      border: `1px solid ${BRAND.sky}`,
      borderRadius: "20px",
      background: BRAND.white,
      alignItems: "center",
    },
    resultTag: {
      background: BRAND.sky,
      color: BRAND.navy,
      borderRadius: "999px",
      padding: "10px 14px",
      fontWeight: 700,
      fontSize: isMobile ? "12px" : "14px",
      whiteSpace: "nowrap",
    },
    answerQuestion: { color: BRAND.navy, fontWeight: 900, fontSize: isMobile ? "14px" : "16px", lineHeight: 1.3 },
    answerMeta: { color: BRAND.taupe, marginTop: "5px", fontSize: isMobile ? "12px" : "14px", lineHeight: 1.35 },
    leaderHeader: { display: "flex", flexDirection: isMobile ? "column" : "row", justifyContent: "space-between", alignItems: isMobile ? "flex-start" : "center", gap: "14px" },
    adminStats: { padding: isMobile ? "8px 20px 8px" : "10px 42px 10px", display: "grid", gridTemplateColumns: isMobile ? "1fr 1fr" : "repeat(4, 1fr)", gap: "12px" },
    statBox: { background: BRAND.white, border: `1px solid ${BRAND.sky}`, borderRadius: "20px", padding: "16px", color: BRAND.navy, display: "flex", flexDirection: "column", gap: "4px", textAlign: "center", fontWeight: 900 },
  };
}
